/**
 * Type-checks the documentation.
 *
 * Every fenced `ts`/`tsx` block in README.md and every `@example` block in a
 * JSDoc comment under src/ is extracted into one generated file, which is then
 * compiled against the real API. Docs that stop compiling stop the build.
 *
 * The examples are prose, so they need a stage to run on: PREAMBLE below
 * declares the fictional domain (the `State` union, the placeholder components)
 * that the examples refer to. Keep it in step with the README when the running
 * example changes — a name the docs use and the preamble lacks shows up as an
 * error here, which is the point.
 *
 * To exempt a block, mark its fence `​```tsx skip-check`.
 *
 * Usage: node scripts/check-docs.mjs
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(root, '.docs-check')
const OUT_FILE = join(OUT_DIR, 'examples.tsx')

const PREAMBLE = `/* Generated by scripts/check-docs.mjs — do not edit, do not commit. */
import type { ReactElement } from 'react'
import { anyOf, iife, renderCond, renderEach, renderMatch, renderShow } from '../src/index.ts'

type State =
  | { status: 'loading' }
  | { status: 'error'; message: string; code: number }
  | { status: 'success'; data: number[] }

type User = { id: number; name: string; active: boolean }

declare const state: State
declare const s: State
declare const user: User | null
declare const users: User[]
declare const byId: Map<number, User>

declare const Spinner: () => ReactElement
declare const Error: (p: { msg: string }) => ReactElement
declare const Content: (p: { data?: number[]; state?: State }) => ReactElement
declare const Fatal: (p: { code: number }) => ReactElement
declare const Profile: (p: { user: User }) => ReactElement
declare const Guest: () => ReactElement
declare const Row: (p: { user: User }) => ReactElement
declare const Empty: () => ReactElement
declare const Busy: (p: { state: State }) => ReactElement
`

/** Fenced blocks in a markdown source, with the line each one starts on. */
function fencedBlocks(markdown) {
  const blocks = []
  const lines = markdown.split('\n')
  let open = null

  lines.forEach((line, i) => {
    const fence = /^```(\S*)\s*(.*)$/.exec(line)
    if (!fence) return
    if (open) {
      blocks.push({ ...open, body: lines.slice(open.start, i).join('\n') })
      open = null
    } else {
      open = { lang: fence[1], info: fence[2].trim(), line: i + 1, start: i + 1 }
    }
  })

  return blocks.filter((b) => ['ts', 'tsx'].includes(b.lang) && b.info !== 'skip-check')
}

function readmeBlocks() {
  return fencedBlocks(readFileSync(join(root, 'README.md'), 'utf8')).map((b) => ({
    ...b,
    origin: `README.md:${b.line}`,
  }))
}

/** `@example` blocks inside JSDoc comments under src/. */
function jsdocBlocks() {
  const out = []
  for (const file of readdirSync(join(root, 'src'))
    .filter((f) => f.endsWith('.ts'))
    .sort()) {
    const text = readFileSync(join(root, 'src', file), 'utf8')
    for (const [, doc] of text.matchAll(/\/\*\*([\s\S]*?)\*\//g)) {
      if (!doc.includes('@example')) continue
      const stripped = doc
        .split('\n')
        .map((l) => l.replace(/^\s*\* ?/, ''))
        .join('\n')
      for (const b of fencedBlocks(stripped)) out.push({ ...b, origin: `src/${file}` })
    }
  }

  return out
}

/**
 * Wrap a block so it stands alone at module scope. Docs show JSX-slot fragments
 * (`{expr}`), which are a block statement rather than an expression on their own,
 * so those get a host element.
 */
function wrap(name, body) {
  const code = body
    .split('\n')
    .filter((l) => !l.startsWith('import '))
    // oxfmt prefixes an expression statement with `;` under semi:false; inside a
    // JSX expression container that is a syntax error.
    .map((l) => l.replace(/^(\s*);\(/, '$1('))
    .join('\n')
    .trimEnd()
  const trimmed = code.trim()

  if (!trimmed) return null
  if (trimmed.startsWith('type State')) return null // the preamble already declares it
  if (trimmed.startsWith('{')) return `export const ${name} = (\n  <div>\n${code}\n  </div>\n)`
  if (/^(const|function|type|interface) /.test(trimmed)) return `export ${trimmed}`

  return `export const ${name} = (\n${code}\n)`
}

const blocks = [...readmeBlocks(), ...jsdocBlocks()]
const parts = [PREAMBLE]
let n = 0

for (const block of blocks) {
  const wrapped = wrap(`_ex${++n}`, block.body)
  if (wrapped) parts.push(`\n/* ${block.origin} */\n${wrapped}\n`)
  else n -= 1
}

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(OUT_FILE, parts.join(''))

try {
  execFileSync(join(root, 'node_modules/.bin/tsgo'), ['-p', 'tsconfig.docs.json'], {
    cwd: root,
    stdio: 'inherit',
  })
  console.log(`docs: ${n} example${n === 1 ? '' : 's'} compile against the API`)
} catch {
  console.error(
    `\ndocs: examples failed to compile.\n` +
      `Each block in ${OUT_FILE.replace(`${root}/`, '')} is preceded by a comment\n` +
      `naming the file it came from — fix the docs there, not the generated file.\n`,
  )
  process.exit(1)
}
